contact_links:
  - name: ğŸ’¡ Feature Request or Enhancement
    url: https://github.com/hikoinc/hikoui/discussions/categories/feature-requests
    about: Suggest a new component, improve an existing component and etc
  - name: ğŸ’¬ Questions & Ideas Discussion
    url: https://github.com/hikoinc/hikoui/discussions
    about: Ask long-form questions and discuss ideas.
  - name: ğŸ® Discord Community Chat
    url: https://discord.gg/HXHzYvNrfV
    about: Ask quick questions or simply chat on the `HikoUI` community Discord server.
  - name: ğŸ¦ Follow Us on X (Twitter)
    url: https://x.com/hikoinc
    about: Link to our X account if you want to follow us and stay up to date with HikoUI news
